package memory

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/arangodb/go-driver"
	"github.com/arangodb/go-driver/http"
)

// InitializeLTMGraph connects to ArangoDB, creates the database if it doesn't exist,
// and ensures all required document and edge collections are present.
func InitializeLTMGraph(ctx context.Context, dbURL, user, pass string) error {
	// 1. Connect to ArangoDB
	conn, err := http.NewConnection(http.ConnectionConfig{
		Endpoints: []string{dbURL},
	})
	if err != nil {
		return fmt.Errorf("failed to create arangodb connection: %w", err)
	}

	client, err := driver.NewClient(driver.ClientConfig{
		Connection:     conn,
		Authentication: driver.BasicAuthentication(user, pass),
	})
	if err != nil {
		return fmt.Errorf("failed to create arangodb client: %w", err)
	}

	// 2. Check if database exists, if not, create it
	dbName := "athena_ltm"
	exists, err := client.DatabaseExists(ctx, dbName)
	if err != nil {
		return fmt.Errorf("failed to check if database exists: %w", err)
	}

	var db driver.Database
	if !exists {
		slog.Info("Database does not exist, creating it...", slog.String("db_name", dbName))
		db, err = client.CreateDatabase(ctx, dbName, nil)
		if err != nil {
			return fmt.Errorf("failed to create database: %w", err)
		}
	} else {
		slog.Info("Database already exists.", slog.String("db_name", dbName))
		db, err = client.Database(ctx, dbName)
		if err != nil {
			return fmt.Errorf("failed to open database: %w", err)
		}
	}

	// 3. Ensure Document Collections (Nodes)
	docCollections := []string{
		"Identities",  // e.g., Sangalo, Athena, OpenClaw
		"Concepts",    // e.g., Agentic AI, Spaced Repetition
		"Tools",       // e.g., Golang, Docker, ArangoDB
		"Projects",    // e.g., Nexus Protocol, joedowns.ai
		"Communities", // Generated by Pregel community detection
	}

	for _, colName := range docCollections {
		err := ensureCollection(ctx, db, colName, driver.CollectionTypeDocument)
		if err != nil {
			return err
		}
	}

	// 3.5 Ensure Indexes for Analytics querying
	err = ensureIndexes(ctx, db, docCollections)
	if err != nil {
		return err
	}

	// 4. Ensure Edge Collection (Relationships)
	edgeCollections := []string{
		"MemoryEdges", // Verbs: USES, WORKS_ON, EXHIBITS (properties: heat_score, confidence)
	}

	for _, colName := range edgeCollections {
		err := ensureCollection(ctx, db, colName, driver.CollectionTypeEdge)
		if err != nil {
			return err
		}
	}

	slog.Info("Successfully initialized LTM graph in ArangoDB.")
	return nil
}

func ensureCollection(ctx context.Context, db driver.Database, colName string, colType driver.CollectionType) error {
	exists, err := db.CollectionExists(ctx, colName)
	if err != nil {
		return fmt.Errorf("failed to check if collection %s exists: %w", colName, err)
	}

	if !exists {
		slog.Info("Collection does not exist, creating it...", slog.String("collection_name", colName))
		_, err = db.CreateCollection(ctx, colName, &driver.CreateCollectionOptions{
			Type: colType,
		})
		if err != nil {
			return fmt.Errorf("failed to create collection %s: %w", colName, err)
		}
	} else {
		slog.Info("Collection already exists.", slog.String("collection_name", colName))
	}

	return nil
}

func ensureIndexes(ctx context.Context, db driver.Database, collections []string) error {
	for _, colName := range collections {
		col, err := db.Collection(ctx, colName)
		if err != nil {
			return fmt.Errorf("failed to get collection %s for indexing: %w", colName, err)
		}

		// 1. Persistent index on community_id
		_, _, err = col.EnsurePersistentIndex(ctx, []string{"community_id"}, &driver.EnsurePersistentIndexOptions{
			Name: "idx_community_id",
		})
		if err != nil {
			return fmt.Errorf("failed to create community_id index on %s: %w", colName, err)
		}

		// 2. Persistent index on is_bridge
		_, _, err = col.EnsurePersistentIndex(ctx, []string{"is_bridge"}, &driver.EnsurePersistentIndexOptions{
			Name: "idx_is_bridge",
		})
		if err != nil {
			return fmt.Errorf("failed to create is_bridge index on %s: %w", colName, err)
		}

		// 3. Persistent index on bridge_score
		_, _, err = col.EnsurePersistentIndex(ctx, []string{"bridge_score"}, &driver.EnsurePersistentIndexOptions{
			Name: "idx_bridge_score",
		})
		if err != nil {
			return fmt.Errorf("failed to create bridge_score index on %s: %w", colName, err)
		}

		// 4. Composite index on is_bridge and bridge_score for sorting
		_, _, err = col.EnsurePersistentIndex(ctx, []string{"is_bridge", "bridge_score"}, &driver.EnsurePersistentIndexOptions{
			Name: "idx_is_bridge_bridge_score",
		})
		if err != nil {
			return fmt.Errorf("failed to create composite bridge index on %s: %w", colName, err)
		}
		
		slog.Info("Successfully ensured analytical indexes", slog.String("collection", colName))
	}
	return nil
}
